### ISSUE TITLE
According to the spigot-mc thread

### ISSUE THREAD

**Issue by dev-json** [DaysOfPeace/SoulSiphon#1]
https://www.spigotmc.org/threads/plugin-is-saving-an-old-version-of-the-config-on-start-please-help.615263/#post-4627686
remove
`this.getConfig().options().copyDefaults();`
from your onEnable method

**Comment by DaysOfPeace** [comment]
I've been playing around with that, and with or without that line it doesn't work :/

**Comment by DaysOfPeace** [comment]
removed
